routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::match(['get', 'post'], 'login')->uses('LoginController@login')->name('login');

Route::match(['get', 'post'], 'system')->uses('SystemController@login')->name('system');


Route::get('logout')->uses('LoginController@logout')->name('logout');
Route::group(['middleware' => 'check.login'], function () {
    Route::get('config')->uses('MainController@config')->name('config');
    Route::get('/')->uses('MainController@home')->name('home');
    Route::any('list')->uses('TableController@lists')->name('list');
    Route::post('del')->uses('TableController@del')->name('del');
    Route::any('form')->uses('TableController@form')->name('form');
    Route::any('xform')->uses('TableController@xform')->name('xform');
    Route::get('upload')->uses('UploadController@view')->name('upload');
    Route::post('upload_touch')->uses('UploadController@upload_touch')->name('upload_touch');
    Route::post('upload_base64')->uses('UploadController@upload_base64')->name('upload_base64');
    Route::get('excel')->uses('ExportController@view')->name('excel');
    Route::get('export')->uses('ExportController@export')->name('export');
    Route::post('import')->uses('ExportController@import')->name('import');
});

//系统设置
Route::group(['middleware' => 'check.login', 'as' => 'system.', 'prefix' => 'system',], function () {
    Route::any('list')->uses('SystemController@lists')->name('list');
    Route::any('edit')->uses('SystemController@edit')->name('edit');
    Route::post('del')->uses('SystemController@del')->name('del');
    Route::post('change')->uses('SystemController@change')->name('change');
    Route::get('info')->uses('SystemController@info')->name('info');
    Route::any('back_db')->uses('SystemController@back_db')->name('back_db');
    Route::any('back_site')->uses('SystemController@back_site')->name('back_site');
    Route::get('download')->uses('SystemController@back_site')->name('download');
    Route::any('config')->uses('SystemController@config')->name('config');
});

app/Http/Controllers/SystemController.php
<?php

namespace App\Http\Controllers;


use App\Models\Configs;
use App\Models\SystemUsers;
use Carbon\Carbon;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Hash;

class SystemController extends Controller
{

    public function config()
    {
        if ($this->isPost()) {
            $fields = $this->request->all();
            unset($fields['_token']);
            foreach ($fields as $name => $value) {
                Configs::updateOrCreate(['name' => $name], [
                    'value' => $value
                ]);
                Configs::clean($name);
            }
            return $this->setJson(0, '保存成功');
        }
        $title = '系统配置';
        $item  = Configs::pluck('value', 'name');
        return view('system.config', compact('title', 'item'));
    }

    public function back_db()
    {
        $title = '数据库备份管理';
        if ($this->isPost()) {
            $nodes = self::getTree(sgConfig('back_db_path'), false);
            return $this->setJson(0, 'ok', $nodes);
        }
        return view('system.db', compact('title'));
    }

    public function back_site()
    {
        $title = '站点备份管理';
        if ($this->isPost()) {
            $nodes = self::getTree(sgConfig('back_site_path'), false);
            return $this->setJson(0, 'ok', $nodes);
        }
        return view('system.site', compact('title'));
    }

    /**
     * 下载
     */
    public function download()
    {
        $md5  = $this->request->input('md5', '');
        $file = Cache::get($md5);
        if (file_exists($file)) {
            sg_download($file);
        } else {
            return '文件不存在';
        }
    }

    /**
     * 获取目录下的结构
     * @param $data_dir string 必须以/结尾
     * @param $spread bool 是否展开
     * @return array
     */
    public static function getTree($data_dir, $spread = false)
    {
        $list = glob($data_dir . '*');
        rsort($list);
        $tree = [];
        if ($list) {
            foreach ($list as $child_dir) {
                $tmp             = [];
                $name            = pathinfo($child_dir, PATHINFO_BASENAME);
                $tmp['name']     = date('Y年m月d日', strtotime($name));
                $tmp['spread']   = $spread;
                $tmp['children'] = [];
                $ls              = glob($child_dir . '/*');
                if ($ls) {
                    $total = 0;
                    foreach ($ls as $file) {
                        if (is_file($file)) {
                            $size        = filesize($file);
                            $total       += $size;
                            $size_format = size2mb($size);
                            $md5         = md5($file);
                            Cache::put($md5, $file, Carbon::now()->addDay(1));
                            $tmp['children'][] = [
                                'name'   => pathinfo($file, PATHINFO_BASENAME) . '(' . $size_format . ')',
                                'spread' => $spread,
                                'md5'    => $md5,
                            ];
                        }
                    }
                    $tmp['name'] .= '(' . size2mb($total) . ')';
                }
                $tree[] = $tmp;
            }
        }
        return $tree;
    }

    /**
     * 管理员列表
     * @return array|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function lists()
    {
        if ($this->isPost()) {
            $name  = $this->request->input('name', '');
            $where = '1';
            if (!empty($name)) {
                $where .= ' and name=' . "'{$name}'";
            }
            $data = SystemUsers::orderBy('id', 'desc')
                ->whereRaw($where)
                ->paginate($this->request->input('limit'));
            $i    = 1;
            foreach ($data as $item) {
                $item->sid            = $i;
                $item->last_format    = Carbon::parse($item->last_at)->diffForHumans();
                $item->created_format = Carbon::parse($item->created_at)->diffForHumans();
                $i++;
            }
            $list    = $data->toArray();
            $content = [
                'code'  => 0,
                'msg'   => '',
                'count' => $list['total'],
                'data'  => $list['data'],
            ];
            return $content;
        }
        $title = '管理员列表';
        return view('system.list', compact('title', 'data'));
    }

    public function info()
    {
        return view('system.info');
    }

    /**
     * 登陆
     * @return $this|Response|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function login()
    {
        if ($this->isPost()) {
            $username = $this->request->input('username');
            $password = $this->request->input('password');
            $captcha  = $this->request->input('captcha');
            if (empty($username)) {
                return $this->setJson(10, '请输入用户名称');
            }
            if (empty($password)) {
                return $this->setJson(10, '请输入用户密码');
            }
            if (empty($captcha)) {
                return $this->setJson(10, '请输入验证码');
            }
            if (!captcha_check($captcha)) {
                return $this->setJson(20, '验证输入错误');
            }
            //验证用户
            $user = SystemUsers::where('name', $username)->first();
            if (!$user) {
                return $this->setJson(10, '用户或密码不存在');
            }
            if ($user->is_use == 0) {
                return $this->setJson(11, '已被管理员禁止登陆');
            }
            if (!Hash::check($password, $user->password)) {
                return $this->setJson(10, '用户或密码不存在!');
            }
            $user->login_count++;
            $user->last_ip = $this->request->getClientIp();
            $user->last_at = Carbon::now();
            $bool          = $user->save();
            if ($bool) {
                session(['user_id' => $user->id]);
                return $this->setJson(0, 'ok', route('home'));
            }
        }
        return view('system.login');
    }

    /**
     * 编辑和添加
     *
     * @return $this|Response|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit()
    {
        $id    = $this->request->input('id', 0);
        $name  = $this->request->input('name', '');
        $pass  = $this->request->input('password', '');
        $pass2 = $this->request->input('password2', '');
        $user  = null;
        if ($id > 0) {
            $title = '编辑管理员';
            $user  = SystemUsers::find($id);
            if ($this->isPost()) {
                if (empty($name)) {
                    return $this->setJson(10, '用户名不能为空');
                }
                $user->name = $name;
                if (!empty($pass2) || !empty($pass)) {
                    if ($pass != $pass2) {
                        return $this->setJson(12, '两次输入密码不一致');
                    }
                    $user->password = bcrypt($pass);
                }
                $bool = $user->save();
                if ($bool) {
                    return $this->setJson(0, '修改成功', route('system.list'));
                }
                return $this->setJson(20, '修改失败');
            }
        } else {
            if ($this->isPost()) {
                if (empty($name)) {
                    return $this->setJson(10, '用户名不能为空');
                }
                if (empty($pass) || empty($pass2)) {
                    return $this->setJson(11, '密码不能为空');
                }
                if ($pass != $pass2) {
                    return $this->setJson(12, '两次输入密码不一致');
                }
                if (strlen($pass2) < 6) {
                    return $this->setJson(13, '密码不能少于6位');
                }
                $secret_pass = bcrypt($pass);
                $bool        = SystemUsers::create([
                    'name'     => $name,
                    'password' => $secret_pass,
                    'is_use'   => 1,
                ]);
                if ($bool) {
                    return $this->setJson(0, '注册成功', route('system.list'));
                }
                return $this->setJson(14, '注册失败');
            }
            $title = '添加管理员';
        }
        return view('system.edit', compact('title', 'user'));
    }

    /**
     * 删除数据
     * @return $this|Response
     */
    public function del()
    {
        $id   = $this->request->input('id', 0);
        $item = SystemUsers::find($id);
        if (!$item) {
            return $this->setJson(10, '数据不存在');
        }
        if ($item->id == 1) {
            return $this->setJson(12, '管理员帐号不允许操作');
        }
        $bool = $item->delete();
        if ($bool) {
            return $this->setJson(0, '操作成功');
        }
        return $this->setJson(400, '异常');
    }

    public function change()
    {
        $id     = $this->request->input('id', 0);
        $status = $this->request->input('value', 0);
        $item   = SystemUsers::find($id);
        if (!$item) {
            return $this->setJson(10, '数据不存在');
        }
        if (!in_array($status, [0, 1])) {
            return $this->setJson(11, '状态值异常');
        }
        if ($item->id == 1) {
            return $this->setJson(12, '管理员帐号不允许操作');
        }
        $item->is_use = $status;
        $bool         = $item->save();
        if ($bool) {
            return $this->setJson(0, '操作成功');
        }
        return $this->setJson(400, '异常');
    }
}

resources/views/system/_base_config.blade.php
<div class="layui-row">
    <div class="layui-col-md4">
        <label class="layui-form-label">数据库备份路径</label>
        <div class="layui-input-block">
            <input type="text" name="back_db_path" lay-verType="tips"
                   placeholder="请输入" value="{{$item['back_db_path'] or ''}}"
                   autocomplete="off" class="layui-input">
        </div>
    </div>
</div>
<div class="layui-row mt5">
    <div class="layui-col-md4">
        <label class="layui-form-label">站点备份路径</label>
        <div class="layui-input-block">
            <input type="text" name="back_site_path" lay-verType="tips"
                   placeholder="请输入" value="{{$item['back_site_path'] or ''}}"
                   autocomplete="off" class="layui-input">
        </div>
    </div>
</div>

resources/views/system/_weixin_config.blade.php
<div class="layui-row">
    <div class="layui-col-md4">
        <label class="layui-form-label">开发者ID</label>
        <div class="layui-input-block">
            <input type="text" name="app_id"  lay-verType="tips"
                   placeholder="请输入开发者ID(AppID)" value="{{$item['app_id'] or ''}}"
                   autocomplete="off" class="layui-input">
        </div>
    </div>
</div>
<div class="layui-row mt5">
    <div class="layui-col-md4">
        <label class="layui-form-label">开发者密码</label>
        <div class="layui-input-block">
            <input type="text" name="app_secret"  lay-verType="tips"
                   placeholder="请输入开发者密码(AppSecret)" value="{{$item['app_secret'] or ''}}"
                   autocomplete="off" class="layui-input">
        </div>
    </div>
</div>
<div class="layui-row mt5">
    <div class="layui-col-md4">
        <label class="layui-form-label">服务器地址</label>
        <div class="layui-input-block">
            <input type="text" value="" placeholder="适合认证订阅或服务号"
                   autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-col-md6">
        <div class="o5 mt2 ml2">适合认证订阅或服务号</div>
    </div>
</div>
<div class="layui-row mt5">
    <div class="layui-col-md4">
        <label class="layui-form-label">服务器地址</label>
        <div class="layui-input-block">
            <input type="text" value="" placeholder="适合个人订阅未认证号"
                   autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-col-md6">
        <div class="o5 mt2 ml2">适合个人订阅未认证号</div>
    </div>
</div>
<div class="layui-row mt5">
    <div class="layui-col-md4">
        <label class="layui-form-label">令牌</label>
        <div class="layui-input-block">
            <input type="text" name="wx_token"  lay-verType="tips" placeholder="令牌(Token)"
                   autocomplete="off" class="layui-input" value="{{$item['wx_token'] or ''}}">
        </div>
    </div>
</div>
<div class="layui-row mt5">
    <div class="layui-col-md4">
        <label class="layui-form-label">消息加解密密钥</label>
        <div class="layui-input-block">
            <input type="text" name="wx_aeskey"  lay-verType="tips"
                   placeholder="消息加解密密钥(EncodingAESKey)" value="{{$item['wx_aeskey'] or ''}}"
                   autocomplete="off" class="layui-input">
        </div>
    </div>
</div>

resources/views/system/config.blade.php
@extends('layout')
@section('title', $title)
@section('style')
@stop
@section('body')
    <blockquote class="layui-elem-quote">{{$title}}</blockquote>
    <form class="layui-form" method="post" action="{{route('system.config')}}">
        <div class="layui-form-item">
            <div class="layui-tab">
                <ul class="layui-tab-title">
                    <li class="layui-this b">基本参数配置</li>
                    <li class="b">微信参数配置</li>
                </ul>
                <div class="layui-tab-content">
                    <div class="layui-tab-item layui-show">
                        @include('system._base_config')
                    </div>
                    <div class="layui-tab-item">
                        @include('system._weixin_config')
                    </div>
                </div>
            </div>
        </div>
        <div class="layui-row mt5 tc">
            <div class="layui-col-md4">
                {{csrf_field()}}
                <button class="layui-btn" lay-submit lay-filter="wxConfig">保存</button>
            </div>
        </div>
    </form>
@stop
@section('script')
    <script>
        layui.use(['table', 'form', 'element'], function () {
            var table = layui.table;
            var form = layui.form;
            var element = layui.element;
            //监听提交
            form.on('submit(wxConfig)', function (data) {
                $.post(data.form.action, data.field, function (rev) {
                    if (rev.status === 0) {
                        layer.msg(rev.msg);
                    } else {
                        layer.msg(rev.msg);
                    }
                });
                return false;
            });
        });
    </script>
@stop

resources/views/system/db.blade.php
@extends('layout')
@section('title', $title)
@section('style')
@stop
@section('body')
    <blockquote class="layui-elem-quote">{{$title}}</blockquote>
    <ul id="main"></ul>
@stop
@section('script')
    <script>
        $(function () {
            $(document).keyup(function (event) {
                if (event.keyCode == 13) {
                    $("#submit").trigger("click");
                }
            });
            layui.use(['tree', 'layer'], function () {
                var tree = layui.tree;
                var layer = layui.layer;
                var option = {
                    elem: '#main' //传入元素选择器
                    , nodes: []
                    , click: function (node) {
                        console.log(node);
                        if (typeof node.md5 !== 'undefined') {
                            layer.confirm('您确定要下载吗?', {btn: ['确定', '取消']}, function (index) {
                                window.location.href = "{{route('system.download')}}?md5=" + node.md5;
                                layer.close(index);
                            }, function (index) {
                                layer.close(index);
                            });
                        }
                    }
                };
                $.post('{{route('system.back_db')}}', function (rev) {
                    if (rev.status === 0) {
                        option.nodes = rev.data;
                        console.log(option);
                        tree(option);
                    }
                });

            });
        });
    </script>
@stop

resources/views/system/edit.blade.php
@extends('layout')
@section('title', $title)
@section('style')
@stop
@section('body')
    <blockquote class="layui-elem-quote">{{$title}}</blockquote>
    <form class="layui-form layui-form-pane ml5" onsubmit="return false;">
        <div class="layui-form-item">
            <label class="layui-form-label">用户名</label>
            <div class="layui-input-inline">
                <input type="text" name="name" required lay-verify="required" lay-verType="tips"
                       placeholder="请输入用户名"
                       autocomplete="off" class="layui-input" value="{{$user->name or ''}}">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">密码框</label>
            <div class="layui-input-inline">
                <input type="password" name="password" placeholder="请输入密码"
                       autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">确认密码</label>
            <div class="layui-input-inline">
                <input type="password" name="password2" placeholder="请输入密码"
                       autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <input type="button" class="layui-btn" lay-submit lay-filter="success" value="立即提交"/>
                <a href="javascript:window.history.back()" class="layui-btn layui-btn-primary">返回</a>
                <input type="hidden" value="{{$user->id or 0}}" name="id">
            </div>
        </div>
    </form>
@stop
@section('script')
    <script>
        $(function () {
            $(document).keyup(function (event) {
                if (event.keyCode == 13) {
                    $("#submit").trigger("click");
                }
            });
            layui.use(['form'], function () {
                var form = layui.form;
                form.on('submit(success)', function (data) {
                    var field = data.field;
                    $.post("{{route('system.edit')}}", field, function (rev) {
                        layer.alert(rev.msg, {skin: 'layui-layer-lan', btn: ['确认']}, function (index) {
                            console.log(typeof(rev.data));
                            if (rev.status === 0) {
                                window.location.href = rev.data;
                            }
                            layer.close(index);
                        }, function (index) {
                            layer.close(index);
                        });
                    });
                    return false;
                });
            });
            $("#reset").click(function () {
                $("input[name='password']").val('');
                $("input[name='password2']").val('');
            });
        });
    </script>
@stop

resources/views/system/list.blade.php
@extends('layout')
@section('title', $title)
@section('style')
    <style>
        .ml5 {
            margin-left: 5px;
        }
    </style>
@stop
@section('body')
    <blockquote class="layui-elem-quote">{{$title}}</blockquote>
    <div class="layui-form">
        <div class="layui-form-item">
            <div class="layui-inline">
                <div class="layui-input-inline">
                    <input type="text" name="name" class="layui-input" placeholder="用户名">
                </div>
                <div class="layui-input-inline">
                    <button class="layui-btn" lay-submit lay-filter="success">搜索</button>
                </div>
            </div>
        </div>
    </div>
    <div class="layui-form-item">
        <a class="layui-btn" href="{{route('system.edit')}}">添加管理员</a>
    </div>
    <div class="layui-collapse">
        <div class="layui-colla-item ">
            <h2 class="layui-colla-title">帮助</h2>
            <div class="layui-colla-content">
                <ul>
                    <li><span class="layui-badge layui-bg-green mr5">1</span>用户管理员列表,可以搜索,可以删除,高级管理员不可以删除</li>
                </ul>
            </div>
        </div>
    </div>
    <table id="table-list" lay-filter="tableLay"></table>
    @verbatim
        <script type="text/html" id="isUseTpl">
            <input type="checkbox" name="" value="{{d.id}}" lay-skin="switch" lay-text="开启|禁止"
                   lay-filter="change" {{d.is_use== 1 ? 'checked' : '' }}>
        </script>
        <script type="text/html" id="barTable">
            <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
            <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
        </script>
    @endverbatim
@stop
@section('script')
    <script>
        layui.use(['table', 'form', 'element'], function () {
            var element = layui.element;
            var table = layui.table;
            var form = layui.form;
            loadList();

            function loadList(where) {
                if (typeof where === 'undefined') {
                    where = {};
                }
                table.render({
                    elem: '#table-list'
                    , height: 'auto'
                    , method: 'post'
                    , url: "{{route('system.list')}}" //数据接口
                    , where: where
                    , page: true //开启分页
                    , size: ''
                    , cellMinWidth: 60
                    , limit: 25
                    , limits: ['25', '50', '100']
                    , cols: [[ //表头
                        {field: 'sid', title: 'ID', sort: true, width: 80}
                        , {field: 'name', title: '订单号', width: 150, align: 'center', sort: true}
                        , {field: 'is_use', title: '帐号状态', width: 120, templet: '#isUseTpl'}
                        , {field: 'last_ip', title: '登陆IP', sort: true, width: 120}
                        , {field: 'last_format', title: '最后登陆时间', sort: true, width: 120}
                        , {field: 'created_format', title: '注册时间', sort: true, width: 150}
                        , {title: '操作', templet: '#barTable', width: 220}
                    ]]
                });
            }

            //操作
            table.on('tool(tableLay)', function (obj) {
                var data = obj.data;
                console.log(data);
                if (obj.event === 'del') {
                    var tips = '真的删除行么';
                    layer.confirm(tips, {icon: 2}, function (index) {
                        $.post("{{route('system.del')}}", {id: data.id}, function (rev) {
                            if (rev.status === 0) {
                                obj.del();
                            }
                            layer.msg(rev.msg);
                        });
                        layer.close(index);
                    });
                } else if (obj.event === 'edit') {
                    window.location.href = "{{route('system.edit')}}?id=" + data.id;
                }
            });
            //监听切换操作
            form.on('switch(change)', function (obj) {
                var pp = {};
                pp.id = this.value;
                pp.value = obj.elem.checked ? 1 : 0;
                $.post("{{route('system.change')}}", pp, function (rev) {
                    if (rev.status === 0) {
                        layer.msg(rev.msg);
                    } else {
                        layer.msg(rev.msg);
                    }
                }, 'json');
            });
            form.on('submit(success)', function (data) {
                var field = data.field;
                loadList(field);
            });
        });
    </script>
@stop

resources/views/system/site.blade.php
@extends('layout')
@section('title', $title)
@section('style')
@stop
@section('body')
    <blockquote class="layui-elem-quote">{{$title}}</blockquote>
    <ul id="main"></ul>
@stop
@section('script')
    <script>
        $(function () {
            $(document).keyup(function (event) {
                if (event.keyCode === 13) {
                    $("#submit").trigger("click");
                }
            });
            layui.use(['tree', 'layer'], function () {
                var tree = layui.tree;
                var layer = layui.layer;
                var option = {
                    elem: '#main' //传入元素选择器
                    , nodes: []
                    , click: function (node) {
                        if (typeof node.md5 !== 'undefined') {
                            layer.confirm('您确定要下载吗?', {btn: ['确定', '取消']}, function (index) {
                                window.location.href = "{{route('system.download')}}?md5=" + node.md5;
                                layer.close(index);
                            }, function (index) {
                                layer.close(index);
                            });
                        }
                    }
                };
                $.post('{{route('system.back_site')}}', function (rev) {
                    if (rev.status === 0) {
                        option.nodes = rev.data;
                        tree(option);
                    }
                });
            });
        });
    </script>
@stop